language: node_js

node_js:
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

install:
  - npm install

after_success:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
